In [11]:
import pandas as pd

fish = pd.read_csv('dataset/fish.csv')
fish.head()

Species  Weight  Length  Diagonal   Height   Width
0   Bream   242.0    25.4      30.0  11.5200  4.0200
1   Bream   290.0    26.3      31.2  12.4800  4.3056
2   Bream   340.0    26.5      31.1  12.3778  4.6961
3   Bream   363.0    29.0      33.5  12.7300  4.4555
4   Bream   430.0    29.0      34.0  12.4440  5.1340

In [12]:
print(pd.unique(fish['Species']))


['Bream' 'Roach' 'Whitefish' 'Parkki' 'Perch' 'Pike' 'Smelt']


In [13]:
fish_input = fish[['Weight', 'Length', 'Diagonal', 'Height'	, 'Width']].to_numpy()

In [14]:
print(fish_input[:5])

[[242.      25.4     30.      11.52     4.02  ]
 [290.      26.3     31.2     12.48     4.3056]
 [340.      26.5     31.1     12.3778   4.6961]
 [363.      29.      33.5     12.73     4.4555]
 [430.      29.      34.      12.444    5.134 ]]


In [15]:
fish_target = fish['Species'].to_numpy()

In [16]:
from sklearn.model_selection import train_test_split
train_input, test_input , train_target, test_target = train_test_split(
    fish_input, fish_target, random_state=42
)


In [17]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
ss.fit(train_input)
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)